alias d='docker'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias dimg='docker images'
alias dimga='docker images -a'
alias dex='docker exec'
alias dk='docker kill'
alias drm='docker rm'
alias drmi='docker rmi'
alias dpl='docker pull'
alias dc='docker commit'
alias dr='docker run'
alias drd='docker run -d'
alias db='docker build'

alias dc='docker-compose'
alias dcu='docker-compose up'
alias dcd='docker-compose down'
