#!/usr/bin/env bash

if [[ -f ./git/MERGE_MODE ]]; then
    exit 0
fi

commit_regex='((^Revert .*[^\.]$)|(^\[(NoRef-0|S5|[A-Z]{2,10}-[0-9]{1,7})\] [A-Z].*[^\. ]$))((\n(.*)?)+)?'

RED='\033[0;31m'
NC='\033[0m' # no color

if [[ "$1" =~ ${commit_regex} ]]; then
    echo -e "${RED}Wrong commit format. Aborting commit...${NC}\n" >&2
    exit 1
fi

