#!/usr/bin/env bash

if [[ $(fd -t f -e 'kt' -e 'kts' . | wc -l) -gt 0 ]]; then
  if ! command -v ktlint &> /dev/null; then
    exit 0
  fi

  stashed_files=$(git diff --name-only -z --cached --relative -- '*.kt' '*.kts')
  if [[ -z "$stashed_files" ]]; then
    exit 0
  fi
  # https://github.com/pinterest/ktlint
  ktlint --relative --patterns-from-stdin="$stashed_files"
fi

if [[ $(fd -t f -e 'tf' . | wc -l) -gt 0 ]]; then
  if ! command -v terraform &> /dev/null; then
    exit 0
  fi
  terraform fmt -recursive
fi

