#!/usr/bin/env bash

# shellcheck disable=SC2009
if ps -o args= $PPID | grep -E -q ' --no-verify| -n | -n$' ; then
    # skip this as --no-verify was given as param
    exit 0
fi

if [[ $(fd -t f -e 'kt' -e 'kts' . | wc -l) -gt 0 ]]; then
    # https://github.com/pinterest/ktlint#command-line-usage
    ktlint -F
fi

if [[ $(fd -t f -e 'tf' . | wc -l) -gt 0 ]]; then
    terraform fmt
fi

