#!/usr/bin/env bash

function printCautionText() {
    cat << END
    ____________________
   /                    \\
   |      CAUTION!      |
   \____________________/
            !  !
            L_ !
           / _)!
          / /__L
_________/ (____)
           (____)
_________  (____)
         \_(____)
            !  !
            \__/

>>>>> You are on ${prefix} <<<<<

END
}

if ps -o args= $PPID | grep -E -q ' --no-verify| -n | -n$' ; then
    # skip this as --no-verify was given as param
    exit 0
else
    # ----- Variables -----
    # branch name
    name=$(git symbolic-ref --short HEAD)
    # branch prefix, e.g. feature, bugfix, etc.
    prefix=$(echo "${name}" | cut -d '/' -f 1)
    # branch suffix == description
    suffix=$(echo "${name}" | cut -d '/' -f 2)

    # check regex
    prefix_regex="^(master|develop|dev|integration|release)"

    # ----- Logic -----
    if [[ ${prefix} =~ $prefix_regex ]]; then
        printCautionText
    fi

    if [ -f .git/MERGE_MSG ]; then
        exit 0
    fi

    if [ ! -f .git/COMMIT_EDITMSG ]; then
        echo 'EDITMSG file does not exist. Exiting commit message preparation.'
        exit 0
    fi

    if [[ $(head -1 .git/COMMIT_EDITMSG) == [* ]]; then
        exit 0
    fi

    sed -i "1i ${suffix//[-_]/ }" .git/COMMIT_EDITMSG
    exit 0
fi
