#!/usr/bin/env bash

if [ -x "$HOME/.config/X11/xprofile" ]; then
	# shellcheck disable=SC1091
	source "$HOME"/.config/X11/xprofile
fi

[ -e "$HOME/.config/X11/Xresources" ] && xrdb -load "$HOME"/.config/X11/Xresources &

numlockx &

[ ! -d "$HOME/data" ] && mkdir -p "$HOME"/data &

compton -CGb &

command -v set-screenlayout &>/dev/null && set-screenlayout &
command -v set-wallpapers &>/dev/null && set-wallpapers &

if [[ $(hostname) == "t480" ]]; then
	amixer sset 'Master' 0% &
	amixer sset 'Capture' 0% &

	command -v activate-touchpad-tapping &>/dev/null && activate-touchpad-tapping &

	exec i3
else
	amixer sset 'Master' 80% &
	amixer sset 'Capture' 80% &

	# Workaround for jvm app to be correctly display in DWM
	export _JAVA_AWT_WM_NONREPARENTING=1
	export AWT_TOOLKIT=MToolkit
	wmname LG3D

	dwmblocks >/dev/null 2>&1 &
	exec dwm
	# exec awesome
fi
