#!/usr/bin/env bash

main() {
	[[ -f .git/MERGE_MODE ]] && exit 0

	local -r commit_message=$(head -1 "$1")

	[[ "$commit_message" =~ ^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?:\ .+[^\.+\ +]$ ]] && exit 0

	echo -e "\nINVALID COMMIT MESSAGE: '$commit_message'"
	echo "See https://www.conventionalcommits.org/en/v1.0.0/#summary for more information."
	exit 1
}

main "$@"
