#!/usr/bin/env bash

main() {
	[[ -f .git/MERGE_MODE ]] && exit 0

	local -r commit_message=$(head -1 "$1")
	local -r commit_types="build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test"
	local -r convetional_commit_regex="^($commit_types){1}(\(.+\))?:\s{1}.+[^\.+\s+]\$"
	if [[ "$commit_message" =~ $convetional_commit_regex ]]; then
		exit 0
	fi

	echo -e "\nInvalid commit message '$commit_message'"
	echo "See https://www.conventionalcommits.org/en/v1.0.0/#summary for more information."
	exit 1
}

main "$@"
