#!/usr/bin/env bash

if [[ $(fd -t f -e 'kt' -e 'kts' . | wc -l) -gt 0 ]]; then
    if ! command -v ktlint &>/dev/null; then
        exit 0
    fi

    if [[ $(git status --short | wc -l) -gt 0 ]]; then
        # https://github.com/pinterest/ktlint
        git diff --name-only -z --cached --relative -- '*.kt' '*.kts' |
            ktlint --relative --patterns-from-stdin=''
    fi
fi

if [[ $(fd -t f -e 'tf' . | wc -l) -gt 0 ]]; then
    if ! command -v terraform &>/dev/null; then
        exit 0
    fi
    terraform fmt -recursive
fi
