#!/usr/bin/env bash

main() {
	# shellcheck disable=SC2009
	if ps -o args= $PPID | grep -E -q ' --no-verify| --amend| -n | -n$'; then
		# skip this as --no-verify was given as param
		exit 0
	fi

	[[ -f .git/MERGE_MSG ]] && exit 0

	if [ ! -f .git/COMMIT_EDITMSG ]; then
		echo "[prepare-commit-msg] EDITMSG file does not exist. Exiting commit message preparation."
		exit 0
	fi

	[[ $(head -1 .git/COMMIT_EDITMSG) == [* ]] && exit 0

	branch_name=$(git symbolic-ref --short HEAD)

	components=$(echo "$branch_name" | tr '/' '\n' | wc -l)

	type=$(echo "$branch_name" | cut -d'/' -f1)

	case "$components" in
	2)
		description=$(echo "$branch_name" | cut -d'/' -f2)
		commit_message="$type: ${description//-/ }"
		;;
	3)
		scope=$(echo "$branch_name" | cut -d'/' -f2)
		description=$(echo "$branch_name" | cut -d'/' -f3)
		commit_message="$type($scope): ${description//-/ }"
		;;
	*)
		commit_message="$branch_name"
		;;
	esac

	sed -i "1i $commit_message" .git/COMMIT_EDITMSG
}

main
