theme = "dracula"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "wlp3s0"
format = "{ssid} {signal_strength} {frequency}"
interval = 5

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"
driver = "upower"
format = "{power} {percentage} {time}"
full_format = "{power}"

[[block]]
block = "time"
interval = 1
format = "%v %T %a"

