icons_format = "{icon}"

[theme]
theme = "dracula"

[icons]
icons = "awesome4"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|} via $device "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
format = " $icon $1m.eng(w:4) "
interval = 1

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"
format = " $icon $percentage {$time |}"
device = "DisplayDevice"
driver = "upower"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a, %d %b %T') "

