---
name: Lint Files
on:
  push:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        uses: oxsecurity/megalinter/flavors/ci_light@v6.18.0 # see https://megalinter.io/latest/flavors/ci_light/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          ENABLE: BASH,REPOSITORY_SECRETLINT,REPOSITORY_GITLEAKS
          PRINT_ALPACA: false
          FLAVOR_SUGGESTIONS: false
