name: Lint Files
on:
  push:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        # see https://megalinter.io/latest/flavors/ci_light/
        uses: oxsecurity/megalinter/flavors/ci_light@e08c2b05e3dbc40af4c23f41172ef1e068a7d651 # v8.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          ENABLE: BASH,REPOSITORY_SECRETLINT,REPOSITORY_GITLEAKS
          PRINT_ALPACA: false
          FLAVOR_SUGGESTIONS: false
