---
name: linter
on:
  push:

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Files
        uses: github/super-linter/slim@v4
        env:
          FILTER_REGEX_EXCLUDE: (nvim/.*)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

